### ISSUE TITLE
Bn's constructor does not check its parameter is a number

### ISSUE THREAD

**Issue by Sidnioulz** [gdanezis/petlib#2]
Which results in `Bn.__init__` serving arbitrary objects to `abs()`. According to the doc, the following types are acceptable:

> "The argument may be a plain or long integer or a floating point number. If the argument is a complex number, its magnitude is returned."

You could either make `Bn` be an `int` or `float`,  make its constructor explicitely reject wrong input types, or build a copy constructor (is that even a thing in Python!?).

**Comment by Sidnioulz** [comment]
https://gist.github.com/Sidnioulz/68df16e3c59ad0714614

**Comment by gdanezis** [comment]
Dealt with this in a pythonic way.
